# Generated by Django 6.1 on 2026-09-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/thumbnails",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="project's name"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=250, verbose_name="short description"),
                ),
                (
                    "article_title",
                    models.CharField(max_length=250, verbose_name="Article Title"),
                ),
                (
                    "article",
                    models.TextField(
                        help_text="split paragraphs with an Enter",
                        verbose_name="Article",
                    ),
                ),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                ("timeline", models.CharField(max_length=50, verbose_name="timeline")),
                ("demo_url", models.URLField(blank=True, verbose_name="demo url")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name=" is published"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="title")),
            ],
            options={
                "db_table": "projects_service",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="tag's name")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="KeyOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_outcomes",
                    models.CharField(max_length=250, verbose_name="key_outcomes"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_outcomes",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_key_outcomes",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/screenshots/",
                        verbose_name="screenshot",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="alt text"
                    ),
                ),
                ("is_primary", models.BooleanField(verbose_name="is primary?")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_screenshots",
                "ordering": ["-is_primary", "display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.service",
                verbose_name="services",
            ),
        ),
        migrations.CreateModel(
            name="StackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stack_items",
                        to="projects.project",
                        verbose_name="project's stacks",
                    ),
                ),
            ],
            options={
                "db_table": "project_stack_items",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.tag",
                verbose_name="Tags",
            ),
        ),
    ]
