# Generated by Django 6.1 on 2026-09-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshots',
            options={'ordering': ['-is_primary', 'display_order', 'id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails', verbose_name='thumbnail'),
        ),
    ]
