# Generated by Django 6.1 on 2026-09-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectKeyOutcome',
            new_name='KeyOutcome',
        ),
        migrations.RenameModel(
            old_name='ProjectScreenshots',
            new_name='Screenshots',
        ),
        migrations.RenameModel(
            old_name='ProjectStackItem',
            new_name='StackItem',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.project', verbose_name="project's services")),
            ],
            options={
                'db_table': 'projects_services',
                'ordering': ['id'],
            },
        ),
    ]
