# Generated by Django 6.1 on 2026-09-11 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContact',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='github',
            field=models.URLField(blank=True, verbose_name='گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='شماره تماس را با فرمت استاندارد مثل +989123456789 وارد کنید.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='تلگرام'),
        ),
    ]
