services:
  backend:
    build:
       context: .
       dockerfile: dockerfile
    env_file:
      - .env
    working_dir: /workspace/app
    container_name: backend
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
    - .:/workspace
    ports:
      - "8000:8000"
    