# Generated by Django 6.1 on 2026-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodel',
            name='description',
            field=models.CharField(max_length=80, verbose_name='description'),
        ),
    ]
