# Generated by Django 6.1 on 2026-08-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skillsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended: 1200 × 1500 px', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
